services:
  - type: web
    name: youtube-downloader-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    buildWithImage: true
    regions: oregon
